### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JaisDK** [Tamaized/MelonGolem#13]
https://gist.github.com/JaisDK/a51eec67ef789f9534e6d17662916529

**Comment by dudebehinddude** [comment]
bro same https://gist.github.com/DUDEbehindDUDE/60daaee9392288198a6868cd2f3f3398
I think it's eithor a conflict with cooking for blockheads or it trying to use forge for 1.15 instead of 1.15.2. (And yes, I have tried launching it without this mod and it works.)
